resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
  - vstest

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  System.Debug: 'false'
  Parameters.Solution: QuantConnect.Indicators.sln
  NugetApiKey: oy2hgxihvu6jrxk2k3lqxcwsyr37tuiuzdli2lbuxnj5xy

steps:
- script: |
    dotnet restore
    dotnet build --output $(Build.ArtifactStagingDirectory)
    dotnet pack --output $(Build.ArtifactStagingDirectory) -c Release /p:Version=1.0.$(Build.BuildId)

- task: PublishBuildArtifacts@1
  displayName: publish artifacts
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    
- task: DotNetCoreCLI@2
  displayName: dotnet nuget push
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: custom
    custom: nuget
    arguments: push $(Build.ArtifactStagingDirectory)\*.nupkg --source https://www.nuget.org --api-key $(NugetApiKey)
